#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(pwd)"
AUDIT_DIR="${ROOT_DIR}/audit_log"

mkdir -p \
  "${AUDIT_DIR}/ai" \
  "${AUDIT_DIR}/security" \
  "${AUDIT_DIR}/architecture" \
  "${AUDIT_DIR}/quality" \
  "${AUDIT_DIR}/sbom"

log() {
  printf '[%s] %s\n' "$(date '+%F %T')" "$*"
}

exists() {
  command -v "$1" >/dev/null 2>&1
}

run_capture() {
  local outfile="$1"
  shift
  "$@" >"$outfile" 2>&1 || true
}

log "Starting audit..."

# Repo inventory
find . \
  -not -path "*/.git/*" \
  -not -path "*/venv/*" \
  -not -path "*/__pycache__/*" \
  > "${AUDIT_DIR}/repo_files.txt"

# Tree
if exists tree; then
  run_capture "${AUDIT_DIR}/tree.txt" tree -a -I '.git|venv|__pycache__|audit_log'
fi

# cloc
if exists cloc; then
  run_capture "${AUDIT_DIR}/cloc.txt" cloc .
fi

# git
run_capture "${AUDIT_DIR}/git_log.txt" git log --oneline -100

# routes
grep -RniE "@router|@app|APIRouter" routers 2>/dev/null \
  > "${AUDIT_DIR}/ai/routes.md" || true

# schemas
find schemas -type f 2>/dev/null \
  > "${AUDIT_DIR}/ai/schemas.md" || true

# modules
find modules -type f -name "*.py" 2>/dev/null \
  > "${AUDIT_DIR}/ai/modules.md" || true

# semgrep
if exists semgrep; then
  run_capture "${AUDIT_DIR}/security/semgrep.md" semgrep scan .
fi

# bandit
if exists bandit; then
  run_capture "${AUDIT_DIR}/security/bandit.json" bandit -r . -f json
fi

# trivy
if exists trivy; then
  run_capture "${AUDIT_DIR}/security/trivy.json" trivy fs --format json .
fi

# gitleaks
if exists gitleaks; then
  run_capture "${AUDIT_DIR}/security/gitleaks.json" gitleaks detect --no-banner --redact --report-format json
fi

# pipdeptree
if exists pipdeptree; then
  run_capture "${AUDIT_DIR}/quality/pipdeptree.txt" pipdeptree
fi

# radon
if exists radon; then
  run_capture "${AUDIT_DIR}/quality/radon.txt" radon cc . -s
fi

# vulture
if exists vulture; then
  run_capture "${AUDIT_DIR}/quality/vulture.txt" vulture .
fi

# pylint
if exists pylint; then
  run_capture "${AUDIT_DIR}/quality/pylint.txt" pylint modules routers main.py
fi

# syft
if exists syft; then
  syft . -o json > "${AUDIT_DIR}/sbom/syft.json" 2>/dev/null || true
fi

# knowledge pack
cat > "${AUDIT_DIR}/ai/knowledge_pack.md" <<EOF
# Injector Detection Knowledge Pack

Entry Point:
- main.py

Routers:
- routers/detect.py
- routers/video.py
- routers/audit.py
- routers/feedback.py
- routers/health.py
- routers/queue.py

Core Modules:
- vehicle_detector
- plate_detector
- cargo_segmenter
- motion_detector
- subtype_classifier
- quality_checker

Model:
- yolov8n.pt

Generated by audit.sh
EOF

tar -czf "${AUDIT_DIR}/audit_bundle.tar.gz" audit_log >/dev/null 2>&1 || true

log "Audit completed."
